import { supabase } from '../../lib/supabase';
import { Post, Comment as SocialComment } from '../../types/social';

/**
 * FeedStore — Supabase-backed social feed.
 * Reads/writes to: posts, comments, likes tables.
 *
 * Post shape on DB:
 *  posts { id, user_id, type, description, image_url, is_public,
 *           workout_id, workout_title, workout_duration, workout_exercises,
 *           workout_volume, muscle_intensities, created_at }
 *  comments { id, post_id, user_id, text, created_at }
 *  likes    { post_id, user_id, created_at }
 *
 * Profile fields joined: display_name, dorm, avatar
 */

// Helper: map a raw Supabase post row → our Post type
const mapRow = (row: any, userId?: string): Post => {
    // Supabase can return joined profiles as an object or as an array depending on foreign key settings
    const profile = Array.isArray(row.profiles) ? row.profiles[0] : row.profiles;
    
    return {
        id: row.id,
        userId: row.user_id,
        userName: profile?.display_name ?? 'FitVerse User',
        userImage: profile?.avatar ?? undefined,
        userDorm: profile?.dorm ?? undefined,
        type: row.type as Post['type'],
        content: {
            description: row.description ?? '',
            image: row.image_url ?? undefined,
            workoutId: row.workout_id ?? undefined,
            workoutData: row.workout_title ? {
                title: row.workout_title,
                duration: row.workout_duration ?? 0,
                exercisesCount: row.workout_exercises ?? 0,
                totalVolume: row.workout_volume ?? 0,
                muscleIntensities: row.muscle_intensities ?? undefined,
            } : undefined,
        },
        // likes are returned as an array of { user_id } objects from the join
        likes: Array.isArray(row.likes)
            ? row.likes.map((l: any) => l.user_id)
            : [],
        // comments are returned as an array of comment rows
        comments: Array.isArray(row.comments)
            ? row.comments.map((c: any) => {
                const commentProfile = Array.isArray(c.profiles) ? c.profiles[0] : c.profiles;
                return {
                    id: c.id,
                    userId: c.user_id,
                    userName: commentProfile?.display_name ?? 'User',
                    userImage: commentProfile?.avatar ?? undefined,
                    text: c.text,
                    createdAt: c.created_at,
                } as SocialComment;
            })
            : [],
        createdAt: row.created_at,
        isPublic: row.is_public ?? false,
    };
};

export type FeedMode = 'friends' | 'community' | 'mine';

export const FeedStore = {
    /**
     * friends  — posts from you + friends (public and friends-only)
     * community — opt-in public posts from everyone
     * mine      — all of your own posts
     */
    async getPosts(
        currentUserId: string,
        friendIds: string[] = [],
        page: number = 1,
        limit: number = 20,
        mode: FeedMode = 'friends'
    ): Promise<Post[]> {
        try {
            let query = supabase
                .from('posts')
                .select(`
                    *,
                    profiles!user_id ( display_name, avatar, dorm ),
                    likes ( user_id ),
                    comments (
                        id, post_id, user_id, text, created_at,
                        profiles!user_id ( display_name, avatar )
                    )
                `)
                .order('created_at', { ascending: false })
                .range((page - 1) * limit, page * limit - 1);

            if (mode === 'community') {
                query = query.eq('is_public', true);
            } else if (mode === 'mine') {
                query = query.eq('user_id', currentUserId);
            } else {
                const allowedIds = [currentUserId, ...friendIds];
                if (allowedIds.length === 1) {
                    query = query.eq('user_id', currentUserId);
                } else {
                    query = query.in('user_id', allowedIds);
                }
            }

            const { data, error } = await query;
            if (error) throw error;
            return (data ?? []).map((row) => mapRow(row, currentUserId));
        } catch (e) {
            console.error('FeedStore.getPosts error:', e);
            throw e;
        }
    },

    /** Save a new post */
    async savePost(post: Post): Promise<void> {
        try {
            const { error } = await supabase.from('posts').insert({
                // id is generated by DB
                user_id: post.userId,
                type: post.type,
                description: post.content.description,
                image_url: post.content.image ?? null,
                is_public: post.isPublic,
                workout_id: post.content.workoutId ?? null,
                workout_title: post.content.workoutData?.title ?? null,
                workout_duration: post.content.workoutData?.duration ?? null,
                workout_exercises: post.content.workoutData?.exercisesCount ?? null,
                workout_volume: post.content.workoutData?.totalVolume ?? null,
                muscle_intensities: post.content.workoutData?.muscleIntensities ?? null,
            });
            if (error) throw error;
        } catch (e) {
            console.error('FeedStore.savePost error:', JSON.stringify(e || {}));
            throw e;
        }
    },

    /** Toggle like on a post */
    async likePost(postId: string, userId: string): Promise<void> {
        try {
            // Check if already liked
            const { data: existing } = await supabase
                .from('likes')
                .select('post_id')
                .eq('post_id', postId)
                .eq('user_id', userId)
                .maybeSingle();

            if (existing) {
                // Unlike
                await supabase
                    .from('likes')
                    .delete()
                    .eq('post_id', postId)
                    .eq('user_id', userId);
            } else {
                // Like — ignore 23505 duplicate key in case of race condition
                const { error } = await supabase
                    .from('likes')
                    .insert({ post_id: postId, user_id: userId });
                if (error && error.code !== '23505') throw error;
            }
        } catch (e) {
            console.error('FeedStore.likePost error:', e);
        }
    },

    /** Add a comment to a post */
    async addComment(postId: string, comment: SocialComment): Promise<void> {
        try {
            const { error } = await supabase.from('comments').insert({
                post_id: postId,
                user_id: comment.userId,
                text: comment.text,
            });
            if (error) throw error;
        } catch (e) {
            console.error('FeedStore.addComment error:', e);
            throw e;
        }
    },

    /** Delete a comment */
    async deleteComment(postId: string, commentId: string): Promise<void> {
        try {
            const { error } = await supabase
                .from('comments')
                .delete()
                .eq('id', commentId);
            if (error) throw error;
        } catch (e) {
            console.error('FeedStore.deleteComment error:', e);
        }
    },

    /** Delete a post (and its comments/likes via CASCADE) */
    async deletePost(postId: string): Promise<void> {
        try {
            const { error } = await supabase
                .from('posts')
                .delete()
                .eq('id', postId);
            if (error) throw error;
        } catch (e) {
            console.error('FeedStore.deletePost error:', e);
        }
    },

    /** Update a post's caption */
    async updatePost(postId: string, newDescription: string): Promise<void> {
        try {
            const { error } = await supabase
                .from('posts')
                .update({ description: newDescription })
                .eq('id', postId);
            if (error) throw error;
        } catch (e) {
            console.error('FeedStore.updatePost error:', e);
        }
    },

    /**
     * Update userName/userImage across all posts for a user when they rename.
     * With Supabase, this is a no-op because we always JOIN profiles on read.
     * Keeping the method signature for backwards compatibility.
     */
    async updateUserPosts(userId: string, newName: string, newImage?: string): Promise<void> {
        // intentional no-op — profile data is joined live from `profiles` table
    },

    /** Clear all feed posts — dev/testing only */
    async clearFeed(): Promise<void> {
        console.warn('FeedStore.clearFeed is a no-op in production Supabase mode.');
    },
};
